package opti

import (
	"os"
	"path/filepath"
	"sort"
)

// ArtifactDir is a build or dependency directory that can be regenerated by its
// toolchain and is therefore safe to remove.
type ArtifactDir struct {
	Path string `json:"path"`
	Name string `json:"name"`
	Kind string `json:"kind"`
	Size int64  `json:"size"`
}

// artifactRules maps an artifact directory base name to a description.
func artifactRules() map[string]string {
	return map[string]string{
		"node_modules":  "Node.js dependencies",
		".next":         "Next.js build cache",
		".nuxt":         "Nuxt build cache",
		".turbo":        "Turborepo cache",
		".parcel-cache": "Parcel cache",
		"dist":          "JS build output",
		"target":        "Rust/Java build output",
		"Pods":          "CocoaPods dependencies",
		"DerivedData":   "Xcode derived data",
		"__pycache__":   "Python bytecode cache",
		".pytest_cache": "pytest cache",
		".mypy_cache":   "mypy cache",
		".gradle":       "Gradle cache",
		".tox":          "tox environments",
		"vendor":        "Vendored dependencies",
		"elm-stuff":     "Elm dependencies",
		".terraform":    "Terraform providers",
	}
}

// FindArtifacts walks root and returns regenerable artifact directories of at
// least minSize bytes, largest first. It does not descend into a matched
// directory.
func FindArtifacts(root string, minSize int64) ([]ArtifactDir, error) {
	expanded, err := ExpandPath(root)
	if err != nil {
		return nil, err
	}
	rules := artifactRules()
	type match struct {
		path string
		name string
		kind string
	}
	matches := make([]match, 0)
	err = filepath.WalkDir(expanded, func(p string, d os.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if !d.IsDir() {
			return nil
		}
		if skipScanDir(p) {
			return filepath.SkipDir
		}
		kind, ok := rules[d.Name()]
		if !ok {
			return nil
		}
		matches = append(matches, match{path: p, name: d.Name(), kind: kind})
		// Never descend into a matched artifact directory.
		return filepath.SkipDir
	})
	if err != nil {
		return nil, err
	}

	paths := make([]string, len(matches))
	for i, m := range matches {
		paths[i] = m.path
	}
	sizes := ConcurrentDirSizes(paths)

	dirs := make([]ArtifactDir, 0, len(matches))
	for _, m := range matches {
		size := sizes[m.path]
		if size >= minSize {
			dirs = append(dirs, ArtifactDir{Path: m.path, Name: m.name, Kind: m.kind, Size: size})
		}
	}
	sort.Slice(dirs, func(i, j int) bool {
		return dirs[i].Size > dirs[j].Size
	})
	return dirs, nil
}

// PurgeArtifacts removes the supplied artifact directories. Removal is confined
// to children of root and honours the trash/permanent setting in CleanOptions.
func PurgeArtifacts(root string, dirs []ArtifactDir, options CleanOptions) (CleanResult, error) {
	expanded, err := ExpandPath(root)
	if err != nil {
		return CleanResult{}, err
	}
	result := CleanResult{Items: make([]CleanItem, 0, len(dirs))}
	for _, dir := range dirs {
		result.TotalBytes += dir.Size
		result.Items = append(result.Items, CleanItem{Path: dir.Path, Kind: dir.Name, Category: "artifacts", Size: dir.Size})
	}
	if !options.Execute {
		return result, nil
	}

	cfg, _ := LoadConfig()
	useTrash := cfg.UseTrash && !options.NoTrash
	var session *TrashSession
	if useTrash {
		session, err = NewTrashSession("artifacts")
		if err != nil {
			useTrash = false
		}
	}

	allowedRoots := []string{expanded}
	for _, dir := range dirs {
		var removeErr error
		if useTrash {
			removeErr = TrashSafe(dir.Path, allowedRoots, session, dir.Size)
		} else {
			removeErr = RemoveAllSafe(dir.Path, allowedRoots)
		}
		if removeErr != nil {
			result.Failures = append(result.Failures, CleanFailure{Path: dir.Path, Error: removeErr.Error()})
			continue
		}
		result.RemovedBytes += dir.Size
		result.RemovedCount++
	}

	if useTrash && session != nil {
		if op, commitErr := session.Commit(); commitErr == nil && op.ID != "" {
			result.Trashed = true
			result.OperationID = op.ID
		}
	}
	return result, nil
}
